Repository SpartCodig-iOS/TeamIntroduction, pull requests merged in 2025-08, with the labels that each got.

#7 [Feature] 멤버 디테일 UI 작업
  TeamIntroduce/TeamIntroduce/Sources/DesignSytstem/Color/Extension+ShapeStyle.swift
  TeamIntroduce/TeamIntroduce/Sources/DesignSytstem/Modifier/CardStyle.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/BlogView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/CollabStyleView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/EditButton.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/IntroductionView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/MemberDetailView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/MemberProfileView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/MemberDetail/StrengthsView.swift
Labels: 🎨 디자인

#6 [FEAT] 데이터 모델 정의 및 데이터 추가
  TeamIntroduce/TeamIntroduce/Sources/Application/TeamIntroduceApp.swift
  TeamIntroduce/TeamIntroduce/Sources/Core/Data/Item.swift
  TeamIntroduce/TeamIntroduce/Sources/Core/Data/TeamMember.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/IntroduceMain/Coordinator/View/IntorduceCoordinatorView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/IntroduceMain/View/ContentView.swift
Labels: ✨ 기능추가

#10 ✨[feat]: Feature/more info 팀약속 뷰 구현
  TeamIntroduce/TeamIntroduce/Sources/DesignSytstem/Color/Extension+ShapeStyle.swift
  TeamIntroduce/TeamIntroduce/Sources/DesignSytstem/Componet/Animation/StaggeredAppearModifier.swift
  TeamIntroduce/TeamIntroduce/Sources/DesignSytstem/Font/PretendardFont.swift
  TeamIntroduce/TeamIntroduce/Sources/DesignSytstem/Modifier/CardStyle.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/IntroduceMain/View/Components/MBTILabel.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/IntroduceMain/View/IntroductionMainView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/TeamAgreement/AgreeMentItem.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/TeamAgreement/TeamAgreeMentView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/TeamBlog/TeamBlogView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/TeamIntroduce/TeamIntroduceView.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/TeamIntroduce/TypingText.swift
  TeamIntroduce/TeamIntroduce/Sources/Presnetaion/WebView/WebView.swift
Labels: ✨ 기능추가, 🎨 디자인
